/**:
  ros__parameters:
    config_path: '/home/ponwalai/fibo-technovation/volume_estimate/src/params/lidar_pose.yaml'

lidar_calibrator:
  ros__parameters:
    max_correspondence_distance: 0.2

pointcloud_clustering_node:
  ros__parameters:
    floor_z_height: 0.05
    cluster_dbscan_eps: 0.7
    cluster_min_points: 20
    normal_weight: 10.0
    normal_estimation_radius: 0.5
    min_pile_angle: 10.0
    max_pile_angle: 45.0

volume_estimator_node:
  ros__parameters:
    voxel_size: 0.2
    floor_height: 0.0